products = [
  {
    '_id': '1',
    'name': 'Anova Precision™ Vacuum Sealer Pro',
    'image': '/images/Anova_Hero_Vacuum_Sealer.webp',
    'description':
    "Sealing your food is serious business, and this sealer know's how to handle business. With more power than the Anova Precision Sealer, and a wider variety of sealing options and accessories, you'll be sealing food like a pro at home.",
    'brand': 'Anova',
    'category': 'Electronics',
    'price': 89.99,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  },
  {
    '_id': '2',
    'name': 'Anova Precision™ Vacuum Sealer',
    'image': '/images/VacSealer_with-Food.webp',
    'description':
    "Comparatively, all other vacuum sealers are blowing it. The Anova Precision™ Vacuum Sealer combines fast air extraction with a strong reliable seal to create the ideal vacuum-sealed bags for sous vide cooking.",
    'brand': 'Apple',
    'category': 'Electronics',
    'price': 599.99,
    'countInStock': 7,
    'rating': 4.0,
    'numReviews': 8,
  },
  {
    '_id': '3',
    'name': 'Anova Precision™ Cooker Lid',
    'image': '/images/Anova_Lid-Nano_Square.webp',
    'description':
    "Like sous vide corn on the cob or your best friend’s new band, this lid is highly underrated. Why? Because covering a sous vide pot reduces energy consumption, accelerates heat up time, and keeps water vapor from escaping on those long (or multi-day) cooks.",
    'brand': 'Cannon',
    'category': 'Electronics',
    'price': 929.99,
    'countInStock': 5,
    'rating': 3,
    'numReviews': 12,
  },
  {
    '_id': '4',
    'name': 'Anova Precision™ Cooker Base',
    'image': '/images/BaseHero_Closeup-with-cooker.webp',
    'description':
     "This base easily attaches to the bottom of the Anova Precision® Cooker and allows your device to stand upright without the use of a clamp for a freestanding sous vide experience.",
    'brand': 'Sony',
    'category': 'Electronics',
    'price': 399.99,
    'countInStock': 11,
    'rating': 5,
    'numReviews': 12,
  },
  {
    '_id': '5',
    'name': 'Anova Precision™ Cooker Insulated Container',
    'image': '/images/Anova _Insulated_Container.webp',
    'description':
     "Made to fit any of our Anova Precision® Cookers, this container is guaranteed to be a new favorite in your arsenal of sous vide tools.",
    'brand': 'Logitech',
    'category': 'Electronics',
    'price': 49.99,
    'countInStock': 7,
    'rating': 3.5,
    'numReviews': 10,
  },
  {
    '_id': '6',
    'name': 'Anova Precision™ Cooker Container 16L',
    'image': '/images/ContainerClear_with_Rack.webp',
    'description':
    "Less evaporation, plenty of room for activities, and more flow than your favorite rapper. The Anova Precision™ Cooker Container was designed in-house to promote the most smooth, even, and circular water flow possible.",
    'brand': 'Amazon',
    'category': 'Electronics',
    'price': 29.99,
    'countInStock': 0,
    'rating': 4,
    'numReviews': 12,
  },
  {
      '_id': '7',
      'name': 'Anova Precision™ Container 12L',
      'image': '/images/12L_Container_3_Quarter_Hero.webp',
      'description':
      "Everything you love about our 16L Container, just in a smaller package. This is the perfect option for saving a little space in storage and on the counter, while still ensuring perfect results – every time.",
      'brand': 'Amazon',
      'category': 'Electronics',
      'price': 29.99,
      'countInStock': 0,
      'rating': 4,
      'numReviews': 12,
    },
  {
        '_id': '8',
        'name': 'Anova Precision™ Perforated Pan',
        'image': '/images/Perf_pan_shopify.webp',
        'description':
        "Made specifically for the Anova Precision™ Oven with a vented surface, allowing your food to experience maximum surface area exposure to heat. Use it to bake everything from a perfectly steamed tray of colorful veggies or dumplings, to beautiful breads and air fried cuts of meat – all quicker than ever.",
        'brand': 'Amazon',
        'category': 'Electronics',
        'price': 29.99,
        'countInStock': 0,
        'rating': 4,
        'numReviews': 12,
      }
]